export enum Example {
    MELBOURNE_METROPOLIAN,
    MELBOURNE_METROPOLIAN_SMALL,
    MELBOURNE_METROPOLIAN_MEDIUM,
    MELBOURNE_METROPOLIAN_LARGE,
    SYNTHETIC_EXAMPLE_SMALL,
    SYNTHETIC_EXAMPLE_MOTIVATING,
}